2021-11-15T17:11:09|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 842, in update_math
    new_val = self.math_func(*lq_vals)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 36, in <lambda>
    func=lambda raw, rmin, rmax, scale: scale*( (raw - rmin)/(rmax-rmin) ),
ZeroDivisionError: float division by zero

2021-11-15T17:11:09|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 46, in connect
    self.dev = PololuMaestroDevice(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 26, in __init__
    self.ser = serial.Serial(port=self.port, timeout=0.5, baudrate=9600,
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2021-11-15T17:11:19|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 46, in connect
    self.dev = PololuMaestroDevice(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 26, in __init__
    self.ser = serial.Serial(port=self.port, timeout=0.5, baudrate=9600,
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2021-11-15T17:12:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 46, in connect
    self.dev = PololuMaestroDevice(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 26, in __init__
    self.ser = serial.Serial(port=self.port, timeout=0.5, baudrate=9600,
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2021-11-15T17:12:25|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 46, in connect
    self.dev = PololuMaestroDevice(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 26, in __init__
    self.ser = serial.Serial(port=self.port, timeout=0.5, baudrate=9600,
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2021-11-15T17:12:26|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 46, in connect
    self.dev = PololuMaestroDevice(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 26, in __init__
    self.ser = serial.Serial(port=self.port, timeout=0.5, baudrate=9600,
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

