2021-12-10T10:56:39|INFO|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer start_stop False
2021-12-10T10:56:39|INFO|HydraHarpOptimizerMeasure|measurement hydraharp_channel_optimizer stopping stop_first
2021-12-10T10:56:39|INFO|HydraHarpHistogramMeasure|hydraharp_histogram start_stop False
2021-12-10T10:56:39|INFO|HydraHarpHistogramMeasure|measurement hydraharp_histogram stopping stop_first
2021-12-10T10:56:39|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-10T10:56:39|INFO|PowerScanMeasure|measurement power_scan stopping stop_first
2021-12-10T10:56:39|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2021-12-10T10:56:39|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping stop_first
2021-12-10T10:56:39|INFO|Sequencer|sequencer start_stop False
2021-12-10T10:56:39|INFO|Sequencer|measurement sequencer stopping stop_first
2021-12-10T10:56:39|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2021-12-10T10:56:39|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping stop_first
2021-12-10T10:56:39|INFO|NearFieldMicroscope|setting up figures for hydraharp_channel_optimizer measurement hydraharp_channel_optimizer
2021-12-10T10:56:39|INFO|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer start_stop False
2021-12-10T10:56:39|INFO|HydraHarpOptimizerMeasure|measurement hydraharp_channel_optimizer stopping stop_first
2021-12-10T10:56:39|INFO|NearFieldMicroscope|setting up figures for hydraharp_histogram measurement hydraharp_histogram
2021-12-10T10:56:39|INFO|NearFieldMicroscope|setting up figures for power_scan measurement power_scan
2021-12-10T10:56:39|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-10T10:56:39|INFO|PowerScanMeasure|measurement power_scan stopping stop_first
2021-12-10T10:56:39|INFO|NearFieldMicroscope|setting up figures for powermeter_optimizer measurement powermeter_optimizer
2021-12-10T10:56:39|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2021-12-10T10:56:39|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping stop_first
2021-12-10T10:56:39|INFO|NearFieldMicroscope|setting up figures for sequencer measurement sequencer
2021-12-10T10:56:39|INFO|Sequencer|sequencer start_stop False
2021-12-10T10:56:39|INFO|Sequencer|measurement sequencer stopping stop_first
2021-12-10T10:56:39|WARNING|HydraHarpOptimizerMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-10T10:56:39|WARNING|HydraHarpHistogramMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-10T10:56:39|WARNING|PowerScanMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-10T10:56:39|WARNING|PowerMeterOptimizerMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-10T10:56:39|WARNING|Sequencer|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-10T10:56:39|WARNING|APDOptimizerCBMeasurement|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-10T10:56:39|INFO|NearFieldMicroscope|setting up figures for apd_optimizer measurement apd_optimizer
2021-12-10T10:56:39|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2021-12-10T10:56:39|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping stop_first
2021-12-10T10:56:39|INFO|NearFieldMicroscope|ini settings loading from near_field_microscope_defaults.ini
2021-12-10T10:56:39|DEBUG|FileLQ|save_dir: update_value 'C:\\Users\\RAMAN\\workspace\\NearField\\NearFieldMicroscope\\data' --> 'E:\\Natalie'    sender=None
2021-12-10T10:56:39|DEBUG|FileLQ|save_dir: different values C:\Users\RAMAN\workspace\NearField\NearFieldMicroscope\data E:\Natalie
2021-12-10T10:56:39|INFO|NearFieldMicroscope|hardware/hydraharp
2021-12-10T10:56:39|INFO|NearFieldMicroscope|hardware/pololu_maestro
2021-12-10T10:56:43|INFO|NearFieldMicroscope|hardware/power_wheel
2021-12-10T10:56:43|INFO|NearFieldMicroscope|hardware/thorlabs_powermeter
2021-12-10T10:56:43|INFO|NearFieldMicroscope|hardware/motorized_polarizer
2021-12-10T10:56:43|INFO|NearFieldMicroscope|hardware/apd_counter
2021-12-10T10:56:43|INFO|NearFieldMicroscope|ini settings loaded from: near_field_microscope_defaults.ini
2021-12-10T10:56:52|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop True
2021-12-10T10:56:52|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer start called from thread: 33132
2021-12-10T10:56:52|DEBUG|ScopeFoundryHW.ni_daq.devices.ni_counter_task|NI_CounterTask.set_channel-- Dev1/ctr0 /Dev1/PFI0
2021-12-10T10:57:00|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2021-12-10T10:57:00|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2021-12-10T10:57:19|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2021-12-10T10:57:19|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping run_thread_run
2021-12-10T10:57:19|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer interrupt called
2021-12-10T10:57:48|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\picoquant\hydraharp_hw.py", line 60, in connect
    debug=S['debug_mode'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\picoquant\hydraharp_dev.py", line 100, in __init__
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\picoquant\hydraharp_dev.py", line 39, in __init__
    self._err(self.hhlib.HH_OpenDevice(self.devnum, hw_serial))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\picoquant\hydraharp_dev.py", line 111, in _err
    raise IOError("HydraHarp Error {}: {}".format(retcode, self.err_message))
OSError: HydraHarp Error -1: HH_ERROR_DEVICE_OPEN_FAIL

2021-12-12T15:58:23|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 53, in <lambda>
    write_func=lambda pos, n=servo_num: self.dev.write_position(n,pos)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 71, in write_position
    self.ask_cmd(cmd)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 44, in ask_cmd
    self.ser.write(bytes(message, 'latin-1'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 317, in write
    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

2021-12-12T15:59:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 53, in <lambda>
    write_func=lambda pos, n=servo_num: self.dev.write_position(n,pos)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 71, in write_position
    self.ask_cmd(cmd)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 44, in ask_cmd
    self.ser.write(bytes(message, 'latin-1'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 317, in write
    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

2021-12-12T15:59:28|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 53, in <lambda>
    write_func=lambda pos, n=servo_num: self.dev.write_position(n,pos)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 71, in write_position
    self.ask_cmd(cmd)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 44, in ask_cmd
    self.ser.write(bytes(message, 'latin-1'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 317, in write
    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

2021-12-12T15:59:42|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 53, in <lambda>
    write_func=lambda pos, n=servo_num: self.dev.write_position(n,pos)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 71, in write_position
    self.ask_cmd(cmd)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 44, in ask_cmd
    self.ser.write(bytes(message, 'latin-1'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 317, in write
    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

2021-12-12T15:59:59|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 53, in <lambda>
    write_func=lambda pos, n=servo_num: self.dev.write_position(n,pos)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 71, in write_position
    self.ask_cmd(cmd)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 44, in ask_cmd
    self.ser.write(bytes(message, 'latin-1'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 317, in write
    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

2021-12-12T16:00:12|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\multi_servo_hw.py", line 53, in <lambda>
    write_func=lambda pos, n=servo_num: self.dev.write_position(n,pos)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 71, in write_position
    self.ask_cmd(cmd)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\pololu_servo\pololu_interface.py", line 44, in ask_cmd
    self.ser.write(bytes(message, 'latin-1'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 317, in write
    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'The device does not recognize the command.', None, 22))

2021-12-14T21:03:03|DEBUG|root|close
